/// Flutter icons Img
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Img
///      fonts:
///       - asset: fonts/Img.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Img {
  Img._();

  static const _kFontFam = 'Img';
  static const String? _kFontPkg = null;

  static const IconData take_1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
